name: Pulumi Preview
on:
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: Infrastructure
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infrastructure
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.WEATHERAPI_CI_SUBSCRIPTIONID }}
          ARM_CLIENT_ID: ${{ secrets.WEATHERAPI_CI_APPID }}
          ARM_CLIENT_SECRET: ${{ secrets.WEATHERAPI_CI_APPSECRET }}
          ARM_TENANT_ID: ${{ secrets.WEATHERAPI_CI_TENANTID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: Infrastructure
